### ISSUE TITLE
Juliana Noceti/ Apucarana-comprovação de renda com GPS

### ISSUE THREAD

**Issue by JosianeCAPS** [SAURAGI/CAPS#1703]
eu tenho um cliente que recolhe a guia de GPS, eu mando o que junto, uma informal?
e voce sabe como que eu calculo o valor ?

se o valor de renda não ultrapassar os 1.787,77, pode ser uma informal sim, mas eu não sei te dizer como que calcula.

**Comment by SAURAGI** [comment]
@LeilaCad oriente a Josiane sobre o a GPS

**Comment by LeilaCad** [comment]
Josiane orientada :)
