### ISSUE TITLE
Cristiane/Presidente Prudente dúvida sac e união estavel

### ISSUE THREAD

**Issue by MarjorieCaps** [SAURAGI/CAPS#1953]
Cliente tem união estável, se ela tiver comprovante de residencia não precisa da união estável né?
Quero rodar a sac para saber se aprova crédito do cliente, tem como?

Sim, não precisa.
Da pra rodar a sac por aqui após a etapa do cadastro estar ok.

**Comment by SAURAGI** [comment]
@MarjorieCaps verificar para fechar o gith caso a orientação já foi realizada.
