### ISSUE TITLE
Andrea Poi / Araçatuba - Op. 27177 e Op. 27153 - Validação de Cadastro

### ISSUE THREAD

**Issue by AlanaCaps** [SAURAGI/CAPS#1984]
Operação 27177 - MICHAEL CANDIDO DINIZ
Operação 27153 - NAIARA DOVALLE SOUSA

A gerente perguntou se o cadastro dessas operações foram validadas pelo CENOP.
O cadastro do Michael foi validado na data de hoje.
O cadastro da Naiara foi enviado para validação na data de hoje.

A gerente solicitou que seja gravada a SAC para o cadastro já validado.

**Comment by SAURAGI** [comment]
@AlanaCaps verificar se é possivel fechar.
