### ISSUE TITLE
Isabela Gouvea/Apucarana - 22593 24003 analisada em atraso

### ISSUE THREAD

**Issue by JosianeCAPS** [SAURAGI/CAPS#1989]
22593 SILVANA DE CASSIA VALENIOTE
-diligencias atendidas desde 23/12
24003 JOAO MARTINS DO NASCIMENTO
-analise da proposta 22/12 e emissao de notas dia 24/12.

as duas operações encontram-se em analise no cenop, com prazo extrapolado.

@SuellenProp gentileza verificar.

**Comment by SuellenProp** [comment]
Operação 24002: E-mail encaminhado à analista Valéria solicitando que entre em contato com o CABB para verificação referente ao prazo de análise extrapolado (Considerando que o CENOP tenha trabalhado normalmente nos dias 24 e 31 o prazo está vencido). 

Operação 22593: Entrei em contato com o CABB para verificar o motivo do atraso e fui orientada a encaminhar e-mail ao CENOP Middle solicitando informações. (Protocolo CABB: 301705990201 - Atendente: Luciano Nocelli)

**Comment by JosianeCAPS** [comment]
ok.
