### ISSUE TITLE
Michelle/Riberão Preto Op: 26184 prazo erro sac

### ISSUE THREAD

**Issue by MarjorieCaps** [SAURAGI/CAPS#1995]
26184 EDNA CLAUDETE DOS REIS BALBAO
Esto tentando aprovar a carta ocorreu um erro quero saber posição do erro.

Tem que aguardar analise da operação para ter nova posição, as esteiras das analistas estão cheias, não temos data para informar quando a operação vai ser analisada novamente.

**Comment by SuellenProp** [comment]
Marjorie, entre em contato com a agente e oriente a mesma para que atualize o histórico e status da operação. 
A analista responsável pela operação (Valéria) encaminhou e-mail no dia 29/12 cobrando posicionamento referente à continuidade da operação, pelo que consta na minha caixa de e-mails não houve retorno; Também não houve atualização do histórico/status no sistema da Saura. (Status atual: proposta com diligência saura)

**Comment by SuellenProp** [comment]
@MarjorieCaps

**Comment by MarjorieCaps** [comment]
Entrei em contato com a agente, a mesma informou que vai informar no histórico da operação, obrigada.
