### ISSUE TITLE
Danielle Okagawa / Arapongas - Op. 24263 - Débito de Tarifa

### ISSUE THREAD

**Issue by AlanaCaps** [SAURAGI/CAPS#1999]
Operação 24263 - DAIANE DA SILVA SANTOS

O débito de tarifa está pendente. A agente informou que já foi verificado na agência, e a conta do cliente está ativa, correta e com saldo, porém o depósito não é efetuado. Foi aberto CABB pela analista para verificar os motivos da recusa do débito, porém o prazo para retorno era até o dia 30/12 conforme histórico da operação. A Danielle solicitou que o histórico seja atualizado, informando os procedimentos que devem ser feitos para que a operação dê seguimento.

**Comment by SuellenProp** [comment]
Encaminhado e-mail a analista para que seja realizada a verificação do motivo de a tarifa não estar sendo cobrada junto ao CABB/CENOP. 
O histórico será atualizado assim que o contato for concluído. Conforme conversado, protocolo fechado.
