### ISSUE TITLE
Vilma/Pérola 26526 dúvida matrícula mãe

### ISSUE THREAD

**Issue by MarjorieCaps** [SAURAGI/CAPS#2024]
26526 ALEX SANDRO RODRIGUES DE SOUZA
No DIMOB está apontando que está faltando anexar a matrícula mãe, posso anexar essa matrícula por aqui?

Não. No portal não tem esse apontamento, a proposta está devolvida, a analista vai informar a diligência.

@SuellenProp essa operação no portal não está informando qual é a diligência a ser sanada, tem como verificar?

**Comment by SuellenProp** [comment]
Situação repassada à analista para que verifique se o documento foi devidamente anexado e atualize o histórico com as devidas informações. 
Necessário informar à agente que se na agência estiver apontando diligência e no Portal BB não estivermos visualizando o ideal é que a agência baixe a diligência informando que a operação está sendo conduzida via COBAN para que as diligências sejam direcionadas ao COBAN.

**Comment by MarjorieCaps** [comment]
ok.

**Comment by JosianeCAPS** [comment]
a agente atendeu a diligencia pela agencia, ja orientada a não atender diligencias via agencia, e quando for apontada para agencia e não para o coban, a diligencia devera ser baixada, com a informação que a operação esta sendo conduzida via coban.

o portal esta sem acesso, não sendo possivel verificação.

**Comment by JosianeCAPS** [comment]
operação ja se encontra em analise no cenop novamente.
