### ISSUE TITLE
Danielle Okagawa/ Cidade de Londrina- Op:23833/23191- Laudo/Atenção. 

### ISSUE THREAD

**Issue by DayaneCAPS** [SAURAGI/CAPS#2031]
23191-JEFFERSON DE SOUZA
Tem como ver se a operação já foi analisada ? Tem como pedir atenção porque a Jaque vai mandar e-mail hoje. (esqueci o nome da pessoa pra quem ela vai mandar e-mail)

@SuellenProp tem ver porque agora a operação esta como em acolhimento só que nenhuma pontamento. Dito a agente que o pedido de atenção já foi feito e que temos que receber um retorno do CENOP até amanhã 07/01. 

______________________________________________________________________________

23833-DEVANIR RISSATO
O laudo já foi anexado, porque esperar o CENOP ?

- Em consulta a operação o laudo, não foi anexado. Questionei a agente se ela tem acesso ao Laudo para nos enviar, ela diz que não. Como foi aberto Cabb pedi para aguardar.

**Comment by SuellenProp** [comment]
23191: Solicitei à analista que dê prioridade à essa operação e verifqiue as diligências apontadas na data de ontem (05/01). 

23833: Analista responsável pela operação ja realizou abertura de chamado BB atende, necessário aguardar.

**Comment by DayaneCAPS** [comment]
É que quando olhei não tinha diligencia apontada ainda.
