### ISSUE TITLE
Juliana Noceti/ Apucarana-simulador BB

### ISSUE THREAD

**Issue by JosianeCAPS** [SAURAGI/CAPS#2035]
o site do banco da simulação esta fora do ar?

ja tivemos mais reclamações hoje, irei  abrir um help desk para verificação.

**Comment by SAURAGI** [comment]
Tentei fazer simulação hoje e deu erro no PMCMV, acho que esta com problemas sim, recebi algumas reclamações.

**Comment by JosianeCAPS** [comment]
@SAURAGI pode ser por causa da atualização das taxas de juros.
não consegui abrir help desk hoje, amanha cedo ja verifico.

**Comment by JosianeCAPS** [comment]
simulador normalizado.
